services:
  web:
    build: .
    command: ['gunicorn', '--bind', ':8000', 'shopsite.wsgi.application']
    volumes:
      - .:/application
      - media_volume:/app/media/
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - shopsite-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/db_data
    networks:
      - shopsite-network
  celery-worker:
    build: .
    command: ['celery', '-A', 'shopsite', 'worker', '--loglevel=info']
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - shopsite-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/db_data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - shopsite-network

  daphne:
    build: .
    command:
      ['daphne', '-b', '0.0.0.0', '-p', '8001', 'shopsite.asgi:application']
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - '8001:8001'
    environment:
      - DJANGO_SETTINGS_MODULE=shopsite.settings
    networks:
      - shopsite-network

volumes:
  db_data:
  redis_data:
  media_volume:

networks:
  shopsite-network:
    driver: bridge
