# Generated by Django 5.2.4 on 2025-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, through='store.CartItem', to='store.product'),
        ),
    ]
