# Generated by Django 5.2.4 on 2025-08-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_orderitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
