# Generated by Django 5.2.4 on 2025-08-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_payment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
    ]
