# Generated by Django 5.2.4 on 2025-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_inventory_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
